
//import java.text.ParseException;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import mypack.TimeClass;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author anilk
 */
public class DBScreen extends javax.swing.JFrame {
    DefaultTableModel model;
    VehicleActions vehicleActions = new AutomobileActions();
    VehicleActions motorbikeActions = new MotorbikeActions();
    VehicleActions minibusActions = new MinibusActions();
    Vehicle vehicle;
    
    public DBScreen() {
        initComponents();
        setResizable(false);
        searchField.setForeground(Color.gray);
        model = (DefaultTableModel)vehicleTable.getModel();
        displayVehicles();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        searchField = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        surnameField = new javax.swing.JTextField();
        licplateField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        vehicleTable = new javax.swing.JTable();
        messageField = new javax.swing.JLabel();
        checkInbutton = new javax.swing.JButton();
        checkOutbutton = new javax.swing.JButton();
        types = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(425, 160));
        setPreferredSize(new java.awt.Dimension(820, 700));

        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("Name      :");

        jLabel2.setText("Surname :");

        jLabel3.setText("Licence Plate :");

        jLabel4.setText("Type            :");

        nameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        nameField.setName(""); // NOI18N

        vehicleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Surname", "Licence Plate", "Type", "Check-In Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(vehicleTable);
        if (vehicleTable.getColumnModel().getColumnCount() > 0) {
            vehicleTable.getColumnModel().getColumn(0).setResizable(false);
            vehicleTable.getColumnModel().getColumn(1).setResizable(false);
            vehicleTable.getColumnModel().getColumn(2).setResizable(false);
            vehicleTable.getColumnModel().getColumn(3).setResizable(false);
            vehicleTable.getColumnModel().getColumn(4).setResizable(false);
        }

        messageField.setText("No check-out has been made.");

        checkInbutton.setText("Check-in Button");
        checkInbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkInbuttonActionPerformed(evt);
            }
        });

        checkOutbutton.setText("Check-out Button");
        checkOutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkOutbuttonActionPerformed(evt);
            }
        });

        types.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "automobile", "motorbike", "truck" }));
        types.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("Dynamic Search:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchField)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 707, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(licplateField)
                            .addComponent(types, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(surnameField)
                            .addComponent(nameField)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(checkInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkOutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(licplateField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkOutbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(types, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(messageField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkInbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void search(String key){
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        vehicleTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(key));
        
    }
    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:
        
        String licplate = searchField.getText().toUpperCase();
        search(licplate);
    }//GEN-LAST:event_searchFieldKeyReleased

    private void checkInbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkInbuttonActionPerformed
        // TODO add your handling code here:
        String name = nameField.getText();
        String surname = surnameField.getText();
        String licplate = licplateField.getText().replaceAll("\\s", ""); //regex characther.
        String type = (String) types.getSelectedItem();
        vehicleActions.checkInpark(name, surname, licplate, type);
        displayVehicles();
        
        
        vehicle = new Vehicle(name, surname, licplate, type, new TimeClass().getTime());
        
        nameField.setText("");
        surnameField.setText("");
        licplateField.setText("");
        
    }//GEN-LAST:event_checkInbuttonActionPerformed

    private void checkOutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkOutbuttonActionPerformed
        // TODO add your handling code here:
        messageField.setText("");
        int selectedRow = vehicleTable.getSelectedRow();
        if(selectedRow == -1){
            if(model.getRowCount() == 0)
                messageField.setText("There is no car in the park.");
            else
                messageField.setText("Please select a car to exit");
        }else{
            
            String licplate = (String)model.getValueAt(selectedRow, 2);
            String type = (String)model.getValueAt(selectedRow, 3);
            
            if (type.equals("automobile")){
                vehicleActions.setLicplate(licplate);
                vehicleActions.checkOutpark();
                messageField.setText("" + vehicleActions.fee());
            }
            
            if(type.equals("motorbike")){
                System.out.println("Motorbike condition");
                motorbikeActions.setLicplate(licplate);
                motorbikeActions.checkOutpark();
                messageField.setText("" + motorbikeActions.fee());
                
            }
            
            if (type.equals("minibus")){
                vehicleActions.setLicplate(licplate);
                vehicleActions.checkOutpark();
                messageField.setText("" + minibusActions.fee());
            }
            
            if(type.equals("truck")){
                vehicleActions.setLicplate(licplate);
                vehicleActions.checkOutpark();
                messageField.setText("" + minibusActions.fee());
            }
            
            displayVehicles();
    }//GEN-LAST:event_checkOutbuttonActionPerformed
}
    /**
     * @param args the command line arguments
     */
    public void displayVehicles(){
        model.setRowCount(0);
        ArrayList<Vehicle> vehicles = new ArrayList<>();
        vehicles = new AutomobileActions().getVehicles();
        
        if (vehicles != null){
            for(Vehicle vehicle:vehicles){
                Object[] add = {vehicle.getOwnerName(),vehicle.getOwnerSurname(),vehicle.getLicplate(),vehicle.getVehicleType(),vehicle.getCheckIntime()};
                model.addRow(add);
            }
        }
    }
    public static void main(String args[]) {
        /*Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DBScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DBScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkInbutton;
    private javax.swing.JButton checkOutbutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField licplateField;
    private javax.swing.JLabel messageField;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField surnameField;
    private javax.swing.JComboBox<String> types;
    private javax.swing.JTable vehicleTable;
    // End of variables declaration//GEN-END:variables
}
